#!/usr/bin/env python3
"""Regenerate src/csa_skilljar/scopes.py from the v2 OpenAPI snapshot.

v2 declares `x-required-scope` on every operation, so the scope a tool needs is a fact in
the spec rather than something to hand-maintain. Baking it at build time is what lets the
server refuse an impossible call locally, naming the exact missing scope, with no network
traffic (design spec 5.4).

Run:  .venv/bin/python scripts/gen_scopes.py
"""
from __future__ import annotations

import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SPEC = ROOT / "specs" / "skilljar-v2-openapi.json"
OUT = ROOT / "src" / "csa_skilljar" / "scopes.py"
VERBS = ("get", "post", "put", "patch", "delete")


def build_table() -> dict[str, tuple[str, ...]]:
    spec = json.loads(SPEC.read_text())
    table: dict[str, tuple[str, ...]] = {}
    for path, item in spec["paths"].items():
        for method, op in item.items():
            if method not in VERBS or not isinstance(op, dict):
                continue
            raw = op.get("x-required-scope") or ()
            if isinstance(raw, str):
                raw = [raw]
            flat = tuple(sorted({s.strip() for entry in raw for s in entry.split(",") if s.strip()}))
            table[f"{method.upper()} {path}"] = flat
    return table


def render(table: dict[str, tuple[str, ...]]) -> str:
    lines = [
        '"""GENERATED by scripts/gen_scopes.py from specs/skilljar-v2-openapi.json.',
        "",
        "Do not edit by hand. Regenerate after refreshing the spec snapshot.",
        '"""',
        "from __future__ import annotations",
        "",
        "REQUIRED_SCOPE: dict[str, tuple[str, ...]] = {",
    ]
    lines += [f"    {k!r}: {table[k]!r}," for k in sorted(table)]
    lines += [
        "}",
        "",
        "",
        "def scopes_for(method: str, path: str) -> tuple[str, ...]:",
        '    """Any-of scopes for an operation. Empty tuple means no scope is required."""',
        '    return REQUIRED_SCOPE.get(f"{method.upper()} {path}", ())',
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    table = build_table()
    OUT.write_text(render(table))
    print(f"wrote {OUT.relative_to(ROOT)} with {len(table)} operations")


if __name__ == "__main__":
    main()
