"""GENERATED by scripts/gen_scopes.py from specs/skilljar-v2-openapi.json.

Do not edit by hand. Regenerate after refreshing the spec snapshot.
"""
from __future__ import annotations

REQUIRED_SCOPE: dict[str, tuple[str, ...]] = {
    'DELETE /v2/clients/{id}': ('clients:write',),
    'DELETE /v2/groups/': ('student-groups:write',),
    'DELETE /v2/groups/{id}/relationships/published-course-visibility/': ('student-groups:write',),
    'DELETE /v2/groups/{id}/relationships/students/': ('student-groups:write',),
    'DELETE /v2/published-courses/{id}': ('published-courses:write',),
    'DELETE /v2/question-banks/': ('question-banks:write',),
    'DELETE /v2/questions/': ('question-banks:write', 'quizzes:write'),
    'DELETE /v2/quizzes/': ('quizzes:write',),
    'DELETE /v2/quizzes/{quiz_id}/question-banks/': ('quizzes:write',),
    'DELETE /v2/students/{id}': ('students:deactivate',),
    'DELETE /v2/web-packages/{id}': ('web-packages:write',),
    'GET /v2/analytics/courses/{course_id}': ('analytics:read',),
    'GET /v2/analytics/courses/{course_id}/ratings/': ('analytics:read',),
    'GET /v2/certificates/': ('certificates:read',),
    'GET /v2/certificates/{id}': ('certificates:read',),
    'GET /v2/clients/': ('clients:read',),
    'GET /v2/clients/{id}': ('clients:read',),
    'GET /v2/courses/': ('courses:read',),
    'GET /v2/courses/{id}': ('courses:read',),
    'GET /v2/domains/': ('domains:read',),
    'GET /v2/domains/{id}': ('domains:read',),
    'GET /v2/enrollments/': ('enrollments:read',),
    'GET /v2/enrollments/{id}': ('enrollments:read',),
    'GET /v2/groups/': ('student-groups:read',),
    'GET /v2/groups/{id}': ('student-groups:read',),
    'GET /v2/groups/{id}/relationships/published-course-visibility/': ('student-groups:read',),
    'GET /v2/lessons/': ('lessons:read',),
    'GET /v2/lessons/{id}': ('lessons:read',),
    'GET /v2/published-courses/': ('published-courses:read',),
    'GET /v2/published-courses/{id}': ('published-courses:read',),
    'GET /v2/question-banks/': ('question-banks:read',),
    'GET /v2/question-banks/{id}': ('question-banks:read',),
    'GET /v2/questions/': ('question-banks:read', 'quizzes:read'),
    'GET /v2/questions/{id}': ('question-banks:read', 'quizzes:read'),
    'GET /v2/quizzes/': ('quizzes:read',),
    'GET /v2/quizzes/{id}': ('quizzes:read',),
    'GET /v2/quizzes/{quiz_id}/question-banks/': ('quizzes:read',),
    'GET /v2/scopes/': ('clients:read',),
    'GET /v2/signup-field-values/': ('signup-fields:read',),
    'GET /v2/signup-field-values/{signup_field_value_id}': ('signup-fields:read',),
    'GET /v2/students/': ('students:read',),
    'GET /v2/students/{id}': ('students:read',),
    'GET /v2/web-packages/': ('web-packages:read',),
    'GET /v2/web-packages/{id}': ('web-packages:read',),
    'PATCH /v2/clients/{id}': ('clients:write',),
    'PATCH /v2/courses/': ('courses:write',),
    'PATCH /v2/enrollments/': ('enrollments:write',),
    'PATCH /v2/enrollments/completion': ('enrollments:write',),
    'PATCH /v2/groups/': ('student-groups:write',),
    'PATCH /v2/lessons/': ('lessons:write',),
    'PATCH /v2/published-courses/': ('published-courses:write',),
    'PATCH /v2/question-banks/': ('question-banks:write',),
    'PATCH /v2/questions/': ('question-banks:write', 'quizzes:write'),
    'PATCH /v2/quizzes/': ('quizzes:write',),
    'PATCH /v2/quizzes/{quiz_id}/question-banks/': ('quizzes:write',),
    'PATCH /v2/signup-field-values/': ('signup-fields:write',),
    'PATCH /v2/students/': ('students:write',),
    'PATCH /v2/web-packages/': ('web-packages:write',),
    'POST /v2/auth/revoke': (),
    'POST /v2/auth/token': (),
    'POST /v2/clients/': ('clients:write',),
    'POST /v2/clients/{id}/rotate-secret': ('clients:write',),
    'POST /v2/courses/': ('courses:write',),
    'POST /v2/enrollments/': ('enrollments:write',),
    'POST /v2/groups/': ('student-groups:write',),
    'POST /v2/groups/{id}/relationships/published-course-visibility/': ('student-groups:write',),
    'POST /v2/groups/{id}/relationships/students/': ('student-groups:write',),
    'POST /v2/lessons/': ('lessons:write',),
    'POST /v2/oauth/register': (),
    'POST /v2/published-courses/': ('published-courses:write',),
    'POST /v2/published-courses/{id}/publish/': ('published-courses:write',),
    'POST /v2/published-courses/{id}/unpublish/': ('published-courses:write',),
    'POST /v2/question-banks/': ('question-banks:write',),
    'POST /v2/questions/': ('question-banks:write', 'quizzes:write'),
    'POST /v2/quizzes/': ('quizzes:write',),
    'POST /v2/quizzes/{quiz_id}/question-banks/': ('quizzes:write',),
    'POST /v2/signup-field-values/': ('signup-fields:write',),
    'POST /v2/students/': ('students:write',),
    'POST /v2/students/{id}/anonymize/': ('students:anonymize',),
    'POST /v2/students/{id}/send-password-reset/': ('students:manage-password',),
    'POST /v2/students/{id}/set-password/': ('students:manage-password',),
    'POST /v2/web-packages/': ('web-packages:write',),
}


def scopes_for(method: str, path: str) -> tuple[str, ...]:
    """Any-of scopes for an operation. Empty tuple means no scope is required."""
    return REQUIRED_SCOPE.get(f"{method.upper()} {path}", ())


def is_known_operation(method: str, path: str) -> bool:
    """Whether the spec declares this operation at all.

    Distinct from `scopes_for` returning an empty tuple, which legitimately means
    "declared, and needs no scope" (the pre-auth token endpoints). Conflating the
    two would let a typo'd path silently skip the scope pre-check.
    """
    return f"{method.upper()} {path}" in REQUIRED_SCOPE
